### ISSUE TITLE
FEATURE 부스맵 상세정보 더하기

### ISSUE THREAD

**Issue by developerChans** [EveryUniv/danfesta#22]
Describe the new feature

마감 기한: ASAP
작업 내용: 부스맵 좌표 추가 및 목록 띄우기.

좌표추가 담당: 김재환, 박찬진
목록띄우기에 대한 건 아직 미협의

**Todos**
- [ ] 부스맵 각 좌표 추가하기
- [ ] 좌표이름은 숫자로 표기
- [ ] 숫자에 해당하는 부스이름들을 목록으로 보여줄지 협의...

** 참고자료 **
![image](https://github.com/EveryUniv/danfesta/assets/68864422/5b39a39f-440f-495b-8ee3-2f798f1f705f)

이름 목록:

1. 취창업지원센터
2. 평생교육원
3. 평생교육원
4. 홍보팀(날개단대)
5. 강남브랜드안과
6. 총학생회
7. 총학생회
8. Gs25
9. Gs25
10. Gs25
11. 패디짱
12. 패디짱
13. M.O.D.E
14. 교수학습개발센터
15. 사주타로
16. 국제교류팀
17. 장애학생지원센터
18. 플리마켓
19. 플리마켓
20. 단냥펀치
21. 단디페
22. 대혁단 사운팀
23. 민사법학회
24. DKBS/DVOICE
25. DKBS/DVOICE
26. 무혼
27. 형사법학회
28. 페이스페인팅 및 캐리커쳐
29. DIDIM
30. 아이사랑
31. 아이사랑
32. 도자기 체험교실
33. 도자기 체험교실
34. 인권센터
35. 산학협력단 SW인재양성사업팀
36. 박물관
37. 취창업지원센터
38. 박물관
39. 모닥불
